---
resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource

resources:
- name: app
  type: git
  source:
    uri: git@github.com:arulvannala/concourse-demo.git
    branch: master
    private_key: ((plat-auto-pipes-deploy-key.private_key))



- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:arulvannala/concourse-demo.git
    branch: version
    file: version
    private_key: ((plat-auto-pipes-deploy-key.private_key))



- name: app-pre-release
  type: github-release
  source:
    owner: arulvannala
    repository: concourse-demo
    access_token: ((dummy-user-access-token))
    pre_release: true
    release: false



- name: app-release
  type: github-release
  source:
    owner: arulvannala
    repository: concourse-demo
    access_token: ((dummy-user-access-token))



jobs:
- name: test

  plan:
  - get: app
    trigger: true
  - task: test-app
    file: app/ci/tasks/test-app.yml

- name: bump-version

  plan:
  - put: version
    params: {bump: major}

- name: build

  plan:
  - get: version
  - get: app
    passed: [test]
    trigger: true
  - task: build-app
    file: app/ci/tasks/build-app.yml
  - put: app-pre-release
    params:
      name: version/version
      tag: version/version
      globs:
      - built-app/app

- name: publish

  plan:
  - get: version
    passed: [build]
  - get: app-pre-release
    passed: [build]
  - put: app-release
    params:
      name: version/version
      tag: version/version
      globs:
      - app-pre-release/app
